name: "Thai Air Pollution ELT"
dataset_paths:
  provinces: "etl_project/data/provinces.csv"
  population: "etl_project/data/population.xlsx"
table_structure:
  path: "etl_project/schemas/table_structure.json"

